### ISSUE TITLE
Huston, we have a problem

### ISSUE THREAD

**Issue by kisPocok** [fordnox/Zend_Auth_Adapter_Facebook#1]
I got this Message: "Unable to Connect to ssl://graph.facebook.com:443. Error #0: php_network_getaddresses: getaddrinfo failed: Name or service not known"

What do you think, what is the problem? Thanks.

**Comment by fordnox** [comment]
Have you changed source code or not ?
I think the right request url is https://graph.facebook.com if you are using secure connection

**Comment by kisPocok** [comment]
I fixed, sorry.
