### ISSUE TITLE
how can i add this in my layout

### ISSUE THREAD

**Issue by a32abdel** [fordnox/Zend_Auth_Adapter_Facebook#7]
how can i do relation between this controller and a layout , for exemple i want to put sign with facebook and when the user authentificate i can redirect him to my controller index/indexAction ,thank you for your help

**Comment by fordnox** [comment]
Hi,

Have you checked https://github.com/fordnox/Zend_Auth_Adapter_Facebook/blob/master/README file i have provided an example there.

**Comment by a32abdel** [comment]
can you explain me this line because i get error in this line $array = $bootstrap->getOption('facebook');, it doesn't accept the getOption 
i have this error 
Fatal error: Call to a member function getOption() on a non-object
